export const SECTION = {
  SERVICE_TYPES: "SERVICE_TYPES",
  BOOKING: "BOOKING",
  REQUEST: "REQUEST",
  UTILITIES: "UTILITIES",
  TOP_BANNER: "TOP_BANNER",
  MIDDLE_BANNER: "MIDDLE_BANNER",
  BOTTOM_BANNER: "BOTTOM_BANNER",
  PRODUCT_LIST: "PRODUCT_LIST",
  STERILIZATION_INFO: "STERILIZATION_INFO",
} as const;

export type SectionType = typeof SECTION[keyof typeof SECTION];
